export const personagens = [
  { 
    id: 1, 
    nome: "Mario", 
    tamanho: "Médio", 
    velocidade: { terra: 7, agua: 7, ar: 7, gravidade: 7 }, 
    aceleracao: 2, 
    peso: 6, 
    manuseio: { terra: 4, agua: 4, ar: 4, gravidade: 4 }, 
    tracao: 2, 
    miniTurbo: 3, 
    invencibilidade: 3,
    imagem: "/img/character/01_Mario_Icon.png" 
  },
  { 
    id: 2, 
    nome: "Luigi", 
    tamanho: "Médio", 
    velocidade: { terra: 7, agua: 7, ar: 7, gravidade: 7 }, 
    aceleracao: 2, 
    peso: 6, 
    manuseio: { terra: 5, agua: 5, ar: 5, gravidade: 5 }, 
    tracao: 1, 
    miniTurbo: 3, 
    invencibilidade: 3,
    imagem: "/img/character/02_Luigi_Icon.png" 
  },
  { 
    id: 3, 
    nome: "Peach", 
    tamanho: "Médio", 
    velocidade: { terra: 6, agua: 6, ar: 6, gravidade: 6 }, 
    aceleracao: 3, 
    peso: 4, 
    manuseio: { terra: 5, agua: 5, ar: 5, gravidade: 5 }, 
    tracao: 3, 
    miniTurbo: 4, 
    invencibilidade: 1,
    imagem: "/img/character/03_Peach_Icon.png" 
  },
  { 
    id: 4, 
    nome: "Daisy", 
    tamanho: "Médio", 
    velocidade: { terra: 6, agua: 6, ar: 6, gravidade: 6 }, 
    aceleracao: 3, 
    peso: 4, 
    manuseio: { terra: 5, agua: 5, ar: 5, gravidade: 5 }, 
    tracao: 3, 
    miniTurbo: 4, 
    invencibilidade: 1,
    imagem: "/img/character/04_Daisy_Icon.png" 
  },
  { 
    id: 5, 
    nome: "Rosalina", 
    tamanho: "Grande", 
    velocidade: { terra: 8, agua: 8, ar: 8, gravidade: 8 }, 
    aceleracao: 1, 
    peso: 7, 
    manuseio: { terra: 3, agua: 3, ar: 3, gravidade: 3 }, 
    tracao: 3, 
    miniTurbo: 2, 
    invencibilidade: 4,
    imagem: "/img/character/05_Rosalina_Icon.png" 
  },
  { 
    id: 9, 
    nome: "Yoshi", 
    tamanho: "Médio", 
    velocidade: { terra: 6, agua: 6, ar: 6, gravidade: 6 }, 
    aceleracao: 3, 
    peso: 4, 
    manuseio: { terra: 5, agua: 5, ar: 5, gravidade: 5 }, 
    tracao: 3, 
    miniTurbo: 4, 
    invencibilidade: 1,
    imagem: "/img/character/09_Yoshi_Icon.png" 
  },
  { 
    id: 10, 
    nome: "Toad", 
    tamanho: "Pequeno", 
    velocidade: { terra: 4, agua: 4, ar: 4, gravidade: 4 }, 
    aceleracao: 4, 
    peso: 3, 
    manuseio: { terra: 7, agua: 7, ar: 7, gravidade: 7 }, 
    tracao: 4, 
    miniTurbo: 4, 
    invencibilidade: 1,
    imagem: "/img/character/10_Toad_Icon.png" 
  },
  { 
    id: 11, 
    nome: "Koopa Troopa", 
    tamanho: "Pequeno", 
    velocidade: { terra: 3, agua: 3, ar: 3, gravidade: 3 }, 
    aceleracao: 4, 
    peso: 2, 
    manuseio: { terra: 8, agua: 8, ar: 8, gravidade: 8 }, 
    tracao: 5, 
    miniTurbo: 4, 
    invencibilidade: 4,
    imagem: "/img/character/11_Koopa_Icon.png" 
  },
  { 
    id: 12, 
    nome: "Shy Guy", 
    tamanho: "Pequeno", 
    velocidade: { terra: 4, agua: 4, ar: 4, gravidade: 4 }, 
    aceleracao: 4, 
    peso: 3, 
    manuseio: { terra: 7, agua: 7, ar: 7, gravidade: 7 }, 
    tracao: 4, 
    miniTurbo: 4, 
    invencibilidade: 1,
    imagem: "/img/character/12_ShyGuy_Icon.png" 
  },
  { 
    id: 17, 
    nome: "Baby Mario", 
    tamanho: "Pequeno", 
    velocidade: { terra: 2, agua: 2, ar: 2, gravidade: 2 }, 
    aceleracao: 5, 
    peso: 1, 
    manuseio: { terra: 8, agua: 8, ar: 8, gravidade: 8 }, 
    tracao: 4, 
    miniTurbo: 5, 
    invencibilidade: 5,
    imagem: "/img/character/17_BabyMario_Icon.png" 
  },
  { 
    id: 18, 
    nome: "Baby Luigi", 
    tamanho: "Pequeno", 
    velocidade: { terra: 2, agua: 2, ar: 2, gravidade: 2 }, 
    aceleracao: 5, 
    peso: 1, 
    manuseio: { terra: 8, agua: 8, ar: 8, gravidade: 8 }, 
    tracao: 4, 
    miniTurbo: 5, 
    invencibilidade: 5,
    imagem: "/img/character/18_BabyLuigi_Icon.png"  
  },
  { 
    id: 19, 
    nome: "Baby Peach", 
    tamanho: "Pequeno", 
    velocidade: { terra: 1, agua: 1, ar: 1, gravidade: 1 }, 
    aceleracao: 4, 
    peso: 0, 
    manuseio: { terra: 10, agua: 10, ar: 10, gravidade: 10 }, 
    tracao: 5, 
    miniTurbo: 5, 
    invencibilidade: 6,
    imagem: "/img/character/19_BabyPeach_Icon.png"  
  },
  { 
    id: 22, 
    nome: "Metal Mario", 
    tamanho: "Médio", 
    velocidade: { terra: 8, agua: 8, ar: 8, gravidade: 8 }, 
    aceleracao: 1, 
    peso: 10, 
    manuseio: { terra: 3, agua: 3, ar: 3, gravidade: 3 }, 
    tracao: 1, 
    miniTurbo: 1, 
    invencibilidade: 3,
    imagem: "/img/character/22_MMario_Icon.png" 
  },
  { 
    id: 23, 
    nome: "Pink Gold Peach", 
    tamanho: "Médio", 
    velocidade: { terra: 8, agua: 8, ar: 8, gravidade: 8 }, 
    aceleracao: 1, 
    peso: 10, 
    manuseio: { terra: 3, agua: 3, ar: 3, gravidade: 3 }, 
    tracao: 1, 
    miniTurbo: 1, 
    invencibilidade: 3,
    imagem: "/img/character/23_PGPeach_Icon.png"
  },
  { 
    id: 25, 
    nome: "Wario", 
    tamanho: "Grande", 
    velocidade: { terra: 10, agua: 10, ar: 10, gravidade: 10 }, 
    aceleracao: 0, 
    peso: 9, 
    manuseio: { terra: 1, agua: 1, ar: 1, gravidade: 1 }, 
    tracao: 1, 
    miniTurbo: 0, 
    invencibilidade: 5,
    imagem: "/img/character/25_Wario_Icon.png" 
  },
  { 
    id: 26, 
    nome: "Waluigi", 
    tamanho: "Grande", 
    velocidade: { terra: 9, agua: 9, ar: 9, gravidade: 9 }, 
    aceleracao: 1, 
    peso: 8, 
    manuseio: { terra: 2, agua: 2, ar: 2, gravidade: 2 }, 
    tracao: 0, 
    miniTurbo: 1, 
    invencibilidade: 4,
    imagem: "/img/character/26_Waluigi_Icon.png" 
  },
  { 
    id: 27, 
    nome: "Donkey Kong", 
    tamanho: "Grande", 
    velocidade: { terra: 9, agua: 9, ar: 9, gravidade: 9 }, 
    aceleracao: 1, 
    peso: 8, 
    manuseio: { terra: 2, agua: 2, ar: 2, gravidade: 2 }, 
    tracao: 0, 
    miniTurbo: 1, 
    invencibilidade: 4,
    imagem: "/img/character/27_DKong_Icon.png" 
  },
  { 
    id: 28, 
    nome: "Bowser", 
    tamanho: "Grande", 
    velocidade: { terra: 10, agua: 10, ar: 10, gravidade: 10 }, 
    aceleracao: 0, 
    peso: 10, 
    manuseio: { terra: 0, agua: 0, ar: 0, gravidade: 0 }, 
    tracao: 0, 
    miniTurbo: 0, 
    invencibilidade: 6,
    imagem: "/img/character/28_Bowser_Icon.png" 
  }
];

export const carrocerias = [
  { 
    id: 1, 
    nome: "Standard Kart", 
    tipo: "Kart",
    velocidade: { terra: 3, agua: 3, ar: 3, gravidade: 3 }, 
    aceleracao: 4, 
    peso: 2, 
    manuseio: { terra: 3, agua: 2, ar: 3, gravidade: 3 }, 
    tracao: 3, 
    miniTurbo: 5, 
    invencibilidade: 3,
    imagem: "/img/vehicle/karts/01_StandardKartBodyMK8.png" 
  },
  { 
    id: 5, 
    nome: "Cat Cruiser", 
    tipo: "Kart",
    velocidade: { terra: 2, agua: 2, ar: 4, gravidade: 3 }, 
    aceleracao: 5, 
    peso: 2, 
    manuseio: { terra: 4, agua: 2, ar: 4, gravidade: 3 }, 
    tracao: 3, 
    miniTurbo: 6, 
    invencibilidade: 3,
    imagem: "/img/vehicle/karts/05_CatCruiserBodyMK8.png" 
  },
  { 
    id: 10, 
    nome: "Biddybuggy", 
    tipo: "Kart",
    velocidade: { terra: 0, agua: 1, ar: 1, gravidade: 2 }, 
    aceleracao: 7, 
    peso: 0, 
    manuseio: { terra: 5, agua: 4, ar: 4, gravidade: 5 }, 
    tracao: 4, 
    miniTurbo: 7, 
    invencibilidade: 0,
    imagem: "/img/vehicle/karts/10_BiddybuggyBodyMK8.png" 
  },
  { 
    id: 11, 
    nome: "Landship", 
    tipo: "Kart",
    velocidade: { terra: 2, agua: 5, ar: 2, gravidade: 0 }, 
    aceleracao: 6, 
    peso: 0, 
    manuseio: { terra: 4, agua: 5, ar: 3, gravidade: 2 }, 
    tracao: 6, 
    miniTurbo: 6, 
    invencibilidade: 3,
    imagem: "/img/vehicle/karts/11_LandshipBodyMK8.png" 
  },
  { 
    id: 20, 
    nome: "Koopa Clown", 
    tipo: "Kart", 
    velocidade: { terra: 3, agua: 4, ar: 3, gravidade: 3 }, 
    aceleracao: 2, 
    peso: 3, 
    manuseio: { terra: 4, agua: 4, ar: 3, gravidade: 3 }, 
    tracao: 7, 
    miniTurbo: 5, 
    invencibilidade: 3,
    imagem: "/img/vehicle/karts/20_MK8DX_Koopa_Clown.png" 
  },
  { 
    id: 21, 
    nome: "Standart Bike", 
    tipo: "Moto", 
    velocidade: { terra: 2, agua: 2, ar: 3, gravidade: 4 }, 
    aceleracao: 5, 
    peso: 1, 
    manuseio: { terra: 4, agua: 3, ar: 3, gravidade: 4 }, 
    tracao: 5, 
    miniTurbo: 5, 
    invencibilidade: 4,
    imagem: "/img/vehicle/bikes/01_StandardBikeBodyMK8.png" 
  },
  { 
    id: 27, 
    nome: "City Tripper", 
    tipo: "Moto", 
    velocidade: { terra: 2, agua: 3, ar: 1, gravidade: 4 }, 
    aceleracao: 6, 
    peso: 1, 
    manuseio: { terra: 5, agua: 4, ar: 2, gravidade: 4 }, 
    tracao: 4, 
    miniTurbo: 6, 
    invencibilidade: 2,
    imagem: "/img/vehicle/bikes/07_MK8_Light-Green_City_Tripper.png" 
  },
  { 
    id: 31, 
    nome: "Yoshi Bike", 
    tipo: "Moto", 
    velocidade: { terra: 2, agua: 2, ar: 4, gravidade: 3 }, 
    aceleracao: 5, 
    peso: 2, 
    manuseio: { terra: 4, agua: 2, ar: 4, gravidade: 3 }, 
    tracao: 3, 
    miniTurbo: 6, 
    invencibilidade: 2,
    imagem: "/img/vehicle/bikes/11_YoshiBikeBodyMK8.png" 
  },
  { 
    id: 33, 
    nome: "Standard ATV", 
    tipo: "ATV", 
    velocidade: { terra: 5, agua: 2, ar: 1, gravidade: 3 }, 
    aceleracao: 0, 
    peso: 4, 
    manuseio: { terra: 0, agua: 1, ar: 0, gravidade: 1 }, 
    tracao: 5, 
    miniTurbo: 3, 
    invencibilidade: 6,
    imagem: "/img/vehicle/atvs/01_StandardATVBodyMK8.png" 
  },
  { 
    id: 35, 
    nome: "Teddy Bugger", 
    tipo: "ATV", 
    velocidade: { terra: 2, agua: 2, ar: 4, gravidade: 3 }, 
    aceleracao: 5, 
    peso: 2, 
    manuseio: { terra: 4, agua: 2, ar: 4, gravidade: 3 }, 
    tracao: 3, 
    miniTurbo: 6, 
    invencibilidade: 2,
    imagem: "/img/vehicle/atvs/03_TeddyBuggyBodyMK8.png" 
  },
  { 
    id: 36, 
    nome: "Bone Rattler", 
    tipo: "ATV", 
    velocidade: { terra: 4, agua: 5, ar: 0, gravidade: 2 }, 
    aceleracao: 1, 
    peso: 4, 
    manuseio: { terra: 1, agua: 5, ar: 1, gravidade: 1 }, 
    tracao: 3, 
    miniTurbo: 3, 
    invencibilidade: 5,
    imagem: "/img/vehicle/atvs/04_MK8BoneRattler.png" 
  }
];

export const pneus = [
  { 
    id: 1, 
    nome: "Standard", 
    velocidade: { terra: 2, agua: 3, ar: 3, gravidade: 2 }, 
    aceleracao: 4, 
    peso: 2, 
    manuseio: { terra: 3, agua: 3, ar: 3, gravidade: 3 }, 
    tracao: 5, 
    miniTurbo: 4, 
    invencibilidade: 4,
    imagem: "/img/vehicle/tires/01_StandardTiresMK8.png" 
  },
  { 
    id: 2, 
    nome: "Monster", 
    velocidade: { terra: 3, agua: 2, ar: 1, gravidade: 2 }, 
    aceleracao: 2, 
    peso: 4, 
    manuseio: { terra: 0, agua: 1, ar: 1, gravidade: 0 }, 
    tracao: 7, 
    miniTurbo: 3, 
    invencibilidade: 6,
    imagem: "/img/vehicle/tires/02_MonsterTiresMK8.png" 
  },
  { 
    id: 3, 
    nome: "Roller", 
    velocidade: { terra: 0, agua: 3, ar: 3, gravidade: 0 }, 
    aceleracao: 6, 
    peso: 0, 
    manuseio: { terra: 4, agua: 4, ar: 4, gravidade: 4 }, 
    tracao: 4, 
    miniTurbo: 6, 
    invencibilidade: 0,
    imagem: "/img/vehicle/tires/03_RollerTiresMK8.png" 
  },
  { 
    id: 4, 
    nome: "Slim", 
    velocidade: { terra: 3, agua: 2, ar: 2, gravidade: 4 }, 
    aceleracao: 2, 
    peso: 2, 
    manuseio: { terra: 4, agua: 4, ar: 4, gravidade: 3 }, 
    tracao: 1, 
    miniTurbo: 3, 
    invencibilidade: 5,
    imagem: "/img/vehicle/tires/04_SlimTiresMK8.png" 
  },
  { 
    id: 5, 
    nome: "Slick", 
    velocidade: { terra: 4, agua: 0, ar: 0, gravidade: 4 }, 
    aceleracao: 1, 
    peso: 3, 
    manuseio: { terra: 2, agua: 0, ar: 1, gravidade: 2 }, 
    tracao: 0, 
    miniTurbo: 2, 
    invencibilidade: 5,
    imagem: "/img/vehicle/tires/05_SlickTiresMK8.png" 
  },
  { 
    id: 6, 
    nome: "Metal", 
    velocidade: { terra: 4, agua: 3, ar: 2, gravidade: 1 }, 
    aceleracao: 0, 
    peso: 4, 
    manuseio: { terra: 2, agua: 2, ar: 0, gravidade: 1 }, 
    tracao: 2, 
    miniTurbo: 2, 
    invencibilidade: 6,
    imagem: "/img/vehicle/tires/06_MetalTiresMK8.png" 
  },
  { 
    id: 7, 
    nome: "Button", 
    velocidade: { terra: 1, agua: 2, ar: 2, gravidade: 2 }, 
    aceleracao: 5, 
    peso: 0, 
    manuseio: { terra: 3, agua: 3, ar: 2, gravidade: 4 }, 
    tracao: 3, 
    miniTurbo: 5, 
    invencibilidade: 3,
    imagem: "/img/vehicle/tires/07_ButtonTiresMK8.png" 
  },
  { 
    id: 17, 
    nome: "Retro Off-Road", 
    velocidade: { terra: 3, agua: 4, ar: 1, gravidade: 2 }, 
    aceleracao: 3, 
    peso: 3, 
    manuseio: { terra: 1, agua: 1, ar: 2, gravidade: 2 }, 
    tracao: 6, 
    miniTurbo: 3, 
    invencibilidade: 6,
    imagem: "/img/vehicle/tires/17_Retro_Off-Road.png" 
  },
  { 
    id: 18, 
    nome: "Gold Tires", 
    velocidade: { terra: 4, agua: 3, ar: 2, gravidade: 1 }, 
    aceleracao: 0, 
    peso: 4, 
    manuseio: { terra: 2, agua: 2, ar: 0, gravidade: 1 }, 
    tracao: 2, 
    miniTurbo: 2, 
    invencibilidade: 5,
    imagem: "/img/vehicle/tires/18_Gold_Tires_MK8.png" 
  }
];

export const planadores = [
  { 
    id: 1, 
    nome: "Super Glider", 
    velocidade: { terra: 1, agua: 1, ar: 2, gravidade: 0 }, 
    aceleracao: 1, 
    peso: 1, 
    manuseio: { terra: 1, agua: 0, ar: 1, gravidade: 1 }, 
    tracao: 1, 
    miniTurbo: 1, 
    invencibilidade: 1,
    imagem: "/img/vehicle/gliders/01_SuperGliderMK8.png" 
  },
  { 
    id: 2, 
    nome: "Cloud Glider", 
    velocidade: { terra: 0, agua: 1, ar: 1, gravidade: 1 }, 
    aceleracao: 2, 
    peso: 0, 
    manuseio: { terra: 1, agua: 0, ar: 2, gravidade: 1 }, 
    tracao: 1, 
    miniTurbo: 2, 
    invencibilidade: 0,
    imagem: "/img/vehicle/gliders/02_Cloud_Glider.png" 
  },
  { 
    id: 3, 
    nome: "Wario Wing", 
    velocidade: { terra: 1, agua: 0, ar: 2, gravidade: 1 }, 
    aceleracao: 1, 
    peso: 2, 
    manuseio: { terra: 1, agua: 1, ar: 1, gravidade: 0 }, 
    tracao: 0, 
    miniTurbo: 1, 
    invencibilidade: 1,
    imagem: "/img/vehicle/gliders/03_WarioWingMK8.png" 
  },
  { 
    id: 5, 
    nome: "Peach Parasol", 
    velocidade: { terra: 0, agua: 0, ar: 1, gravidade: 1 }, 
    aceleracao: 2, 
    peso: 0, 
    manuseio: { terra: 1, agua: 0, ar: 2, gravidade: 1 }, 
    tracao: 0, 
    miniTurbo: 2, 
    invencibilidade: 0,
    imagem: "/img/vehicle/gliders/05_PeachParasolGliderMK8.png" 
  },
  { 
    id: 9, 
    nome: "Bowser Kite", 
    velocidade: { terra: 0, agua: 0, ar: 1, gravidade: 1 }, 
    aceleracao: 2, 
    peso: 0, 
    manuseio: { terra: 1, agua: 0, ar: 2, gravidade: 1 }, 
    tracao: 0, 
    miniTurbo: 2, 
    invencibilidade: 0,
    imagem: "/img/vehicle/gliders/09_BowserKiteMK8.png" 
  },
  { 
    id: 10, 
    nome: "Plane Glider", 
    velocidade: { terra: 1, agua: 0, ar: 2, gravidade: 1 }, 
    aceleracao: 1, 
    peso: 2, 
    manuseio: { terra: 1, agua: 1, ar: 1, gravidade: 0 }, 
    tracao: 0, 
    miniTurbo: 1, 
    invencibilidade: 1,
    imagem: "/img/vehicle/gliders/10_PlaneGliderMK8.png" 
  },
  { 
    id: 12, 
    nome: "Gold Glider", 
    velocidade: { terra: 1, agua: 0, ar: 2, gravidade: 1 }, 
    aceleracao: 1, 
    peso: 2, 
    manuseio: { terra: 1, agua: 1, ar: 1, gravidade: 0 }, 
    tracao: 0, 
    miniTurbo: 1, 
    invencibilidade: 1,
    imagem: "/img/vehicle/gliders/12_GoldGliderMK8.png" 
  },
  { 
    id: 15, 
    nome: "Paper Glider", 
    velocidade: { terra: 0, agua: 1, ar: 1, gravidade: 1 }, 
    aceleracao: 2, 
    peso: 0, 
    manuseio: { terra: 1, agua: 0, ar: 2, gravidade: 1 }, 
    tracao: 1, 
    miniTurbo: 2, 
    invencibilidade: 0,
    imagem: "/img/vehicle/gliders/15_PaperGliderIcon-MK8.png" 
  }
];